name: about-build

on:
  push:
    branches:
      - 'about'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      LSI: 'true'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Cache Ruby Bundler
      id: cache
      uses: actions/cache@v2
      env:
        CACHE_ID: 2.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-
    - name: Change rubygems loading
      run: sed -i "/^source/c source 'https://rubygems.org'" Gemfile  && ruby -v && bundle -v
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: bundle install --retry=3 
    - name: Run jekyll-build
      run: bundle config set --local path 'vendor/bundle' && ruby -v && bundle -v && bundle exec jekyll -v&& bundle exec jekyll build --trace
    - name: Simple deploy with git
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with: # optional
        git-user: ${{ secrets.Git_USERNAME}}
        git-email: ${{ secrets.Git_EMAIL }}
        git-base-folder: '_site'
        commit-message: '<auto:> ABOUT pages build/deploy by github action.'
        BRANCH: 'gh-pages'
        FOLDER: public